version: '2'
services:
  crashplan:
    build: 
      context: ./docker-crashplan
    environment:
      - TZ=Auckland/Pacific
    ports:
      - 4242:4242
      - 4243:4243
    volumes:
      - /var/crashplan
      - /mnt/data:/mnt/data
